### ISSUE TITLE
Add darkmode on the offical npm website

### ISSUE THREAD

**Issue by KevinRebakure** [npm/documentation#1285]
I personally prefer to keep all my working environments in dark mode and whenever I go to a site without a dark mode feature. I just can't take it, it bothers me a lot. 

I would like us to that feature on the official npm website, because personally it's my go to, for looking up documentations fast for packages I need.
 
I'm not alone though😅

**Comment by leobalter** [comment]
Hi @KevinRebakure! While I understand the dark mode might bring convenience, it's a feature that requires a non-minor lift such as a major review - and potential rewrite - on the whole website structure without compromising accessibility. At the same time, you may try workarounds such as using reader mode on your browser. 

Because of that, this feature is not yet making the cut for our roadmap.

Given that, this issue tracker is not the most adequate for such feature request. I suggest you use the [Community discussions](https://github.com/orgs/community/discussions/categories/npm) as there is a thread for this. Adding requests here won't help.
