### ISSUE TITLE
[FEATURE] Document enviroment variables set by `npx` and `npm exec`

### ISSUE THREAD

**Issue by Ginden** [npm/documentation#56]
# What / Why

`npx` sets many enviroment variables.

It can be seen by running command:
```
meld <(npx -c 'env | sort') <(env | sort) <(npm exec -c 'env | sort')
```

### Current Behavior

There is no documentation on this.

### Expected Behavior

It should be documented.

## Who

* n/a

## References

* n/a

**Comment by wraithgar** [comment]
The things we export that users can rely on are documented here https://docs.npmjs.com/cli/v7/using-npm/scripts#environment

Some other things are set, but not documented because they are not something we want to support and may be changed.

If there are things exported that you feel belong on the list in the existing docs, please specify them explicitly so we can discuss if it is an actual oversight, or if it is intended to be undocumented.

**Comment by Ginden** [comment]
> Some other things are set, but not documented because they are not something we want to support and may be changed.

Understandable, closing issue.
